### ISSUE TITLE
配套一个系列的教程文章，页面都不存在了

### ISSUE THREAD

**Issue by zhuyuanwen** [PanJiaChen/vueAdmin-template#101]
![image](https://user-images.githubusercontent.com/12319327/40461504-42889f68-5f3e-11e8-960d-d3a8854195ba.png)

![image](https://user-images.githubusercontent.com/12319327/40461406-dba9042c-5f3d-11e8-93b2-dbc636ca1836.png)

@PanJiaChen 想从大神写的文档一点点看起，但是发现几个地方，点击开来，文档页面都不存在了 T_T
请问文档原文还在么？能重新发布么？

**Comment by PanJiaChen** [comment]
这些文章挂载掘金平台上，现在他们平台挂了应该马上会修复。
暂时你可以在这里看文章https://segmentfault.com/blog/hand-to-hand

**Comment by zhuyuanwen** [comment]
非常感谢！！
