### ISSUE TITLE
webpack No parser and no file path given, couldn't infer a parser

### ISSUE THREAD

**Issue by yanlee26** [PanJiaChen/vueAdmin-template#104]
`
 error  in ./src/views/layout/components/Sidebar/SidebarItem.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.`类似这种

**Comment by PanJiaChen** [comment]
请提供更多信息。

**Comment by vueadmin** [comment]
![image](https://user-images.githubusercontent.com/18540773/40595649-740f0266-6268-11e8-9e08-b7b6643cc78d.png)

**Comment by vueadmin** [comment]
前段时间用还没有问题，近期也没有更新，我怀疑是不是因为依赖安装失败导致的。

**Comment by vueadmin** [comment]
prettier.js 出的问题 但是我能力解决

**Comment by ToPeas** [comment]
[暂时的解决方案](https://stackoverflow.com/questions/50555953/vue-webpack-template-missing-parser)

**Comment by PanJiaChen** [comment]
https://github.com/vuejs-templates/webpack/issues/1389
