### ISSUE TITLE
在默认布局的基础上添加一个header,如何修改呢?

### ISSUE THREAD

**Issue by dengyakui** [PanJiaChen/vueAdmin-template#105]
默认是左右布局,左边是sidebar,右边是container, 我想在最上部添加一个header, 展示网站logo和一些快捷菜单,该如何修改呢?? @PanJiaChen

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vueAdmin-template/blob/master/src/views/layout/Layout.vue 
这里加入header 并自行调整css就可以了。
