### ISSUE TITLE
升级element到2.1.0后table组件报错

### ISSUE THREAD

**Issue by yxmg** [PanJiaChen/vueAdmin-template#108]
背景：模版版本3.0.0，element-ui在2.0之后table组件存在着各种问题，包括宽高自适应异常、性能不好
在element-ui新的版本中对此进行了优化。
问题：如题，在升级element-ui的时候遇到问题，table组件报错如下：
![image](https://user-images.githubusercontent.com/29594167/41011851-5d4099f4-6971-11e8-9016-97d292b52e4d.png)
报错描述为style的父对象为undefined，定位到node_modules\element-ui\packages\table\src\table-layout.js的第64行。
代码如下：
```else if (typeof value === '
    if (value === '') {
        el.style[prop] = '';
      }
      this.updateHeight();
    }
```
对比过往版本，改动：
![image](https://user-images.githubusercontent.com/29594167/41012289-7636b1c6-6973-11e8-8448-29639005f1c9.png)

猜测是模版之前的element-ui影响，看到最新版本的模版已经支持element-ui2.3.x，但由于改动太大，无法对模版进行更新，想问下这个问题是由什么引起的？

**Comment by PanJiaChen** [comment]
不是很理解你的问题，`element-ui`的问题很本项目有什么关系？

**Comment by yxmg** [comment]
https://github.com/ElemeFE/element/issues/9659
