### ISSUE TITLE
怎么实现跨域啊

### ISSUE THREAD

**Issue by 392241868** [PanJiaChen/vueAdmin-template#109]

**Comment by 392241868** [comment]
axios实现跨域请求

**Comment by 392241868** [comment]
$.ajax({
                type : "POST",
                async:true,
                url :httpUrl+'/user/login/',
                dataType:"jsonp",
                data:"uid="+username+"&pw="+hex_md5(password),
                jsonp: "callback",//服务端用于接收callback调用的function名的参数
                jsonpCallback:"success_jsonpCallback",//callback的function名称
});之前是用这个实现跨域，现在我想用你这个后台管理模版改造之前用jquery实现的后台

**Comment by 392241868** [comment]
你是用https://easy-mock.com/mock/5950a2419adc231f356a6636/vue-admin 这个url，我本地可以访问，也是使用跨域，你这个怎么实现的呢？

**Comment by yxmg** [comment]
跨域的话，可以让后端配置下CORS

**Comment by 392241868** [comment]
thanks

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/#/zh-cn/cors
