### ISSUE TITLE
代码改动后无法触发编译器编译

### ISSUE THREAD

**Issue by jl1014171068** [PanJiaChen/vueAdmin-template#110]
试过更换编辑器均无法触发编译、其他项目可以正常编译

node：8.0
node:10.1.0
均试过

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vueAdmin-template/blob/fb32462266fc8eee7b1a5631528fb531bca6068d/config/index.js#L21
改为`true`试试
