### ISSUE TITLE
打包之后无法登陆

### ISSUE THREAD

**Issue by JayTam** [PanJiaChen/vueAdmin-template#112]
我只修改了 config/prod.env.js 的 build 中
从 assetsPublicPath: '/vueAdmin-template/' 改成 assetsPublicPath: './'
打包之后，直接运行index.html，只有下面的请求
![image](https://user-images.githubusercontent.com/31993846/41214499-5022c1a0-6d7e-11e8-9b78-c362d53aade8.png)
没有dev运行中的info请求，路由也没跳转，还是停留在登陆页面
![image](https://user-images.githubusercontent.com/31993846/41214555-92e5d748-6d7e-11e8-8fe3-daf0b1940915.png)

**Comment by PanJiaChen** [comment]
所有问题是什么

**Comment by JayTam** [comment]
打包之后，点击了登陆，页面不跳转，登陆不了
dev的话，正常

**Comment by PanJiaChen** [comment]
Duplicate of #54

**Comment by JayTam** [comment]
谢谢，我就说cooike没有token
