### ISSUE TITLE
问下项目axios跨越问题怎么解决的

### ISSUE THREAD

**Issue by wusong4988398** [PanJiaChen/vueAdmin-template#118]
问下，我在该项目中访问我另外一个后台项目的ajax方法，老是提示这个，错误：
XMLHttpRequest cannot load http://localhost:57335/api/TokenAuth/Authenticate. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9528' is therefore not allowed access. The response had HTTP status code 500.
这个应该是跨域的问题，请问在项目里如何设置啊，网上搜了也没解决苦恼了好几天。

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/#/zh-cn/cors
