### ISSUE TITLE
问下，这个项目是如何打包的

### ISSUE THREAD

**Issue by wusong4988398** [PanJiaChen/vueAdmin-template#120]

**Comment by PanJiaChen** [comment]
使用webpack打包，具体见[文档](https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/deploy.html#%E6%9E%84%E5%BB%BA) 和 [vuejs-templates](http://vuejs-templates.github.io/webpack/commands.html)

[代码](https://github.com/PanJiaChen/vue-element-admin/tree/master/build)
