### ISSUE TITLE
用户名，密码保存问题

### ISSUE THREAD

**Issue by myq3636** [PanJiaChen/vueAdmin-template#122]
我使用用户名密码登录进入主页后，显示出来用户名和密码，并且刷新页面用户名和密码不会丢失刷新页面，store里面的数据不是会丢失吗？，这个是怎么实现不丢失的？代码体现在哪块？

**Comment by PanJiaChen** [comment]
我会把一个标志用户的唯一token存贮在 `cookie`信息。刷新页面的时候会根据这个 `token` 再去拉取一次用户信息，存到`store`中。

详细见[文章](https://juejin.im/post/591aa14f570c35006961acac)。
