### ISSUE TITLE
三级路由的相关问题

### ISSUE THREAD

**Issue by mcmf** [PanJiaChen/vueAdmin-template#126]
如果三级路由配合面包屑使用   比如二级路由下有一个table  table有个按钮查看列表类似这种， 点击查看按钮新出来一个相当于三级路由的页面。这个页面会出现二级路由的table    我是为了使用面包屑这样设计，但是怎么在三级路由页面不使用二级路由页面的渲染呢

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/800
