### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by smilerks** [PanJiaChen/vueAdmin-template#128]
`const app = {
  state: {
    sidebar: {
      opened: !+Cookies.get('sidebarStatus'),
      withoutAnimation: false
    },
    device: 'desktop'
  },`
这段代码在src/store/modules/app.js中，请问一下
`opened: !+Cookies.get('sidebarStatus'),`
中的’!+’是什么意思，我刚接触vue不久，希望您能解答下，谢谢

**Comment by PanJiaChen** [comment]
和vue没关系。

`+` 是隐式转化 将 `'0' => 0`  字符串转成数字类型。

'!'  取反 返回 布尔类型 `!0 => true`  `!1 => false`
