### ISSUE TITLE
页面刷新之后跳转回首页

### ISSUE THREAD

**Issue by sxd14159** [PanJiaChen/vueAdmin-template#135]
在使用vuex进行全局状态管理时，会出现刷新后store清空的情况。
看了一下原版的vueAdmin没有这种bug 请问刷新后不丢失state.token是怎么实现的？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vueAdmin-template/blob/4bc17952edf25212e5dbd271b68eb64875be4cb3/src/permission.js#L11

本项目会将用户信息存储在 `cookie` 中，刷新页面的时候会重新去读取`cookie` 中的 `token`。
