### ISSUE TITLE
Sidebar 与 vue-router path问题

### ISSUE THREAD

**Issue by GR-Rui** [PanJiaChen/vueAdmin-template#142]
![image](https://user-images.githubusercontent.com/11731807/43706036-d4e8edc6-9996-11e8-8fcf-f7e90961ef63.png)
path ID 如果是动态值，菜单选项无法高亮，请问下怎么解决？

**Comment by PanJiaChen** [comment]
不匹配是正常现象。

需要自行写匹配逻辑。

https://github.com/PanJiaChen/vueAdmin-template/blob/master/src/views/layout/components/Sidebar/index.vue#L6

**Comment by GR-Rui** [comment]
Thx
