### ISSUE TITLE
从侧边栏的二级菜单进入二级菜单页面然后再二级菜单点击跳转到详情页侧边栏不高亮

### ISSUE THREAD

**Issue by zhenxionglv** [PanJiaChen/vueAdmin-template#143]
[从侧边栏的二级菜单进入二级菜单页面然后再二级菜单点击跳转到详情页侧边栏不高亮

**Comment by zhenxionglv** [comment]
1.这个是点击二级路由的时候侧边栏是可以高亮的
![default](https://user-images.githubusercontent.com/22031113/43818113-bd6b4a70-9b0f-11e8-89f9-3612c99ceb13.png)
2.这个是点击二级路由页面下详情后跳转到详情页面的时候
![default](https://user-images.githubusercontent.com/22031113/43818165-f7f5312e-9b0f-11e8-8580-4d46b5f2b268.png)

**Comment by PanJiaChen** [comment]
详情页不高亮是正常现象。

有需求需要自行调整逻辑。

https://github.com/PanJiaChen/vueAdmin-template/blob/4bc17952edf25212e5dbd271b68eb64875be4cb3/src/views/layout/components/Sidebar/index.vue#L6
