### ISSUE TITLE
抱歉小白请教个问题

### ISSUE THREAD

**Issue by kid1412621** [PanJiaChen/vueAdmin-template#144]
想问下 login 页面上有个 el-form 组件,但我找不到是在哪里注册的(全局/局部的都没找到),只看到在 main.js 里面有注册 element-ui 插件.想请教下这个组件的使用是不是通过插件的注册来注册的?

**Comment by PanJiaChen** [comment]
vue 是可以全局注册的，你在注册element-ui的时候，它会将这些组件注册到全局。

https://github.com/ElemeFE/element/blob/dev/src/index.js

https://github.com/ElemeFE/element/blob/3990d9bdea11585c8444db54c0eed7a4281c059a/packages/alert/index.js#L4-L6

**Comment by kid1412621** [comment]
@PanJiaChen 感谢回复，还是有点懵，你说得的注册 element-ui 是注册它成为组件呢？还是插件？
全局注册我只知道在 main.js 中用 Vue.component 或通过 webpack 注册，但是我未能找到注册的代码。:disappointed:

**Comment by PanJiaChen** [comment]
我代码都贴给你了。。

**Comment by kid1412621** [comment]
@PanJiaChen 嗯嗯,我也看了,只是没用过这种方法,官方文档只提到了四种插件的使用方法:

**Comment by PanJiaChen** [comment]
https://cn.vuejs.org/v2/guide/components-registration.html#%E5%85%A8%E5%B1%80%E6%B3%A8%E5%86%8C

**Comment by kid1412621** [comment]
@PanJiaChen 谢谢哥孜孜不倦,应该明白了
