### ISSUE TITLE
502报错

### ISSUE THREAD

**Issue by yangdengcheng** [PanJiaChen/vueAdmin-template#145]
裤衩哥，能否教一下如何把登录取消掉

**Comment by PanJiaChen** [comment]
你指不需要登录 就直接进入后台页面？

**Comment by PanJiaChen** [comment]
移除这段逻辑

https://github.com/PanJiaChen/vueAdmin-template/blob/4bc17952edf25212e5dbd271b68eb64875be4cb3/src/permission.js#L9-L37
