### ISSUE TITLE
我把mock js 去掉了 改成自己的服务 怎么登陆成功之后 一直请求 sockejs t=1234434435 

### ISSUE THREAD

**Issue by chengkai3396** [PanJiaChen/vueAdmin-template#146]
这是什么原因啊  
![qq 20180816102643](https://user-images.githubusercontent.com/24379114/44183783-efeb0000-a13e-11e8-82d9-59603fd2509b.png)

**Comment by PanJiaChen** [comment]
这是webpack hmr。
