### ISSUE TITLE
iconfont.js放哪里啊？

### ISSUE THREAD

**Issue by fxjs** [PanJiaChen/vueAdmin-template#15]
请问 iconfont.js文件替换在哪里啊？目录结构好像有问题

**Comment by PanJiaChen** [comment]
新版本已不用` iconfont.js`
在这里添加 就好了 https://github.com/PanJiaChen/vueAdmin-template/tree/master/src/icons/svg

**Comment by fxjs** [comment]
是用iconfile有什么弊端吗

**Comment by PanJiaChen** [comment]
主要是不直观，完全不知道里面有哪些icon

**Comment by PanJiaChen** [comment]
可以参照[文档](https://panjiachen.github.io/vue-element-admin-site/#/icon)

**Comment by hqiqeq** [comment]
阿里图标下载的svg， 在侧边栏使用，尺寸好像设置不了1em （侧边栏的图标尺寸是1em）
