### ISSUE TITLE
线上地址访问不了了

### ISSUE THREAD

**Issue by splinfengwang** [PanJiaChen/vueAdmin-template#16]

**Comment by PanJiaChen** [comment]
`.github.io` 有时候会被墙，请自带梯子

**Comment by splinfengwang** [comment]
一直都趴在付费梯子上。不过现在正常了，下次如果再出现，我会把错误记录下来。你先关闭这个issue吧。

**Comment by PanJiaChen** [comment]
可能是[easy-mock](https://easy-mock.com/) 前面挂了
