### ISSUE TITLE
另一个账号不能登陆 

### ISSUE THREAD

**Issue by yoyoping** [PanJiaChen/vueAdmin-template#18]
另一个账号不能登陆，我是个新手 想看看两个不同账号登陆是否会有不同的展示 ，我现在在看权限的地方，有些思维我可能还没转换过来 ，我想知道真实开发过程中判断权限，后台是返回什么过来呢？？？

**Comment by PanJiaChen** [comment]
开两个不同的游览器就可以实现多账号登录了。
第二个问题比较宽泛，建议可以先看看该文章 https://segmentfault.com/a/1190000009506097

**Comment by yoyoping** [comment]
我通过看您的代码  大概了解的是您是登录后获取role  存到vuex   我看到您的路由表里面有meta的role权限，但是我改了那个路由表的admin  怎么登录admin还是有table这个菜单

**Comment by PanJiaChen** [comment]
建议自己一步一步debug，通过描述是很难定位你的问题的。

**Comment by yoyoping** [comment]
嗯  好的  谢谢了
