### ISSUE TITLE
表單驗證無法發生作用

### ISSUE THREAD

**Issue by ming7824** [PanJiaChen/vueAdmin-template#19]

**Comment by ming7824** [comment]
onSubmit(form) {
            
          this.$refs[form].validate(valid => {
              if (valid) {


                  console.log('page/form.vue/onSubmit');
                  this.loading = true;
                  this.$store.dispatch('NewEvent', this.form).then(() => {
                      /* 觸發modules/user.js  actions 的Login */
                      this.loading = false;
                      this.$router.push({ path: '/event/eventlist' });
                  }).catch(() => {
                      this.loading = false;
                  });
              } else {
                  console.log('error submit!!');
                  return false;
              }
          });
不管有沒有填都會送出,只是沒填的會秀出錯誤訊息.

**Comment by PanJiaChen** [comment]
请自行参照 element-ui 文档 和本项目无关
