### ISSUE TITLE
在服务器环境下npm run build以后，在浏览器访问显示一片空白

### ISSUE THREAD

**Issue by Shiotsuki** [PanJiaChen/vueAdmin-template#2]
打包没报错，浏览器也没报错，网页没有任何内容。
审查元素看打包的东西也没有注入网页，是我打开姿势不对吗...?

**Comment by PanJiaChen** [comment]
实测并没有问题，能提供一些更具体的信息么？

**Comment by Shiotsuki** [comment]
sorry,检查了一下是我自己的问题

**Comment by wangwei8888** [comment]
有这个问题的，npm run dev之后 浏览器打开了页面 其实webpack还没编译完成
