### ISSUE TITLE
[feedback] 关于手脚架去除用户权限相关的建议

### ISSUE THREAD

**Issue by BelinChung** [PanJiaChen/vueAdmin-template#22]
hi, 有一个小建议
手脚架需要尽可能的简单和通用化处理。
这个项目中关于用户权限的逻辑可能并不适用于一些项目，而且逻辑对于新手来说有点复杂。
因为我在尝试自己删除相关代码的过程中，也遇到了递归菜单导致死循环的问题，我觉得这对新手会造成一定的调试难度。
所以建议能去除掉这块的相关逻辑代码，有需要的同学可以去参考 PanJiaChen/vue-element-admin 项目。

**Comment by PanJiaChen** [comment]
新版本已移除动态权限的相关代码
相关代码已移至[permission-control](https://github.com/PanJiaChen/vueAdmin-template/tree/permission-control)分支
