### ISSUE TITLE
修改本地存储的cookie的value后，再刷新页面会进入卡死状态，也无法跳转

### ISSUE THREAD

**Issue by guoshuai6511** [PanJiaChen/vueAdmin-template#26]
自己试着修改本地存的cookie时，发现再刷新只有进度条一直在加载，页面并无跳转，私以为一旦发现有人修改cookie时自动跳转到登录页为好。现在是只有把cookie清除掉重新登陆或者改回来才可以往下走。

**Comment by PanJiaChen** [comment]
已修复 576e37762acb47ba1d7083006b1ed9d1a72579cd
