### ISSUE TITLE
有没有考虑升级到Element-UI 2.0.1

### ISSUE THREAD

**Issue by baiqb** [PanJiaChen/vueAdmin-template#27]
饿了么Element-UI 升级到2.0.1了，有没有考虑升级到2.0呢

**Comment by PanJiaChen** [comment]
目前不升级主要处于如下两个考虑
1. `element`刚大版本升级还不是很稳定，目前版本table都还有内存泄漏等问题
2. `vue-element-admin`项目最近正在重构优化，所以等它升级完成之后本项目也会升级

**Comment by baiqb** [comment]
这样啊，我们目前在用的项目，有些已经升级到2.0了，会不会有什么大影响

**Comment by PanJiaChen** [comment]
如果是新项目没有历史遗留问题的话应该还好，如果是从@1.x.x升级上来的话自己注意一下官方的 breaking changes

**Comment by baiqb** [comment]
@PanJiaChen 好的，谢谢！

**Comment by PanJiaChen** [comment]
已升级
