### ISSUE TITLE
请教一个有关addroutes的问题

### ISSUE THREAD

**Issue by blueroseslol** [PanJiaChen/vueAdmin-template#28]
参考你的代码，用在自己项目中的时候我发现一个问题：

addroutes之后，可以访问对应的路由，但是$router.options.routes里并没有更新。

但是你的项目里是正常的，你也没有像别的项目中使用$router.options.routes=asyncRouterMap的方式来解决问题。所以请问你是怎么解决这个问题的？可以大概说一下么？本人百思不得其解

**Comment by PanJiaChen** [comment]
的确会有这个问题 `addRoutes`的路由不会在`router.options.routes`中显示

**Comment by blueroseslol** [comment]
我的问题是你的项目里是运行正常的（SlideMeunItem，你也是通过router.options.routes遍历的），这个是怎么做到的呢？网上找到的解决方案你一个都没用啊？

**Comment by PanJiaChen** [comment]
menu又不是根据`router.options.routes`获得的，是直接通过`router.js` 获得的

**Comment by blueroseslol** [comment]
我去看了你最新的代码，是用的是store中的state.permission.routers那就没问题了。谢谢大神！
