### ISSUE TITLE
npm run build 出現錯誤?

### ISSUE THREAD

**Issue by ming7824** [PanJiaChen/vueAdmin-template#31]
ERROR in static/js/21.540266a8052725d15ece.js from UglifyJs
Unexpected token: punc (() [./~/element-ui/packages/col/src/col.js:23,0][static/js/21.540266a8052725d15ece.js:50,10]

ERROR in static/js/22.9c86a61d88ab46dbe81b.js from UglifyJs
Unexpected token: punc (() [./~/element-ui/packages/col/src/col.js:23,0][static/js/22.9c86a61d88ab46dbe81b.js:50,10]

ERROR in static/js/24.68610023a38715dfe228.js from UglifyJs
Unexpected token: punc (() [./~/element-ui/packages/col/src/col.js:23,0][static/js/24.68610023a38715dfe228.js:50,10]

**Comment by PanJiaChen** [comment]
UglifyJs 不支持打包 es6的语法 请先 用babel 编译一下
