### ISSUE TITLE
分页样式没有，不是引入了默认的css吗，怎么会事呢？

### ISSUE THREAD

**Issue by mmd0308** [PanJiaChen/vueAdmin-template#32]
分页样式没有，不是引入了默认的css吗，怎么会事呢？

传不了图片，我简单描述一下，麻烦了：
现在样式是这样的：
Total 50 10 /page 1234 Go to 1
正确的应该是
共 50 条 10 条/页 1234 前往 1 页

**Comment by PanJiaChen** [comment]
需要提供更详细的描述

**Comment by mmd0308** [comment]
传不了图片，我简单描述一下，麻烦了：
现在样式是这样的：
Total 50 10 /page 1234   Go to  1
正确的应该是 
共 50 条  10 条/页 1234  前往 1 页

**Comment by PanJiaChen** [comment]
这是中英文的问题吧。。。和样式有什么关系
http://element.eleme.io/1.4/#/zh-CN/component/i18n

**Comment by mentallxm** [comment]
main.js
import locale from 'element-ui/lib/locale/lang/zh-CN'
Vue.use(ElementUI, { locale })

然后分页样式，得按照element的html结构来：
    <div v-show="!listLoading" class="pagination-container">
      <el-pagination @size-change="handleSizeChange" @current-change="handleCurrentChange" :current-page.sync="listQuery.page"
        :page-sizes="[10,20,30,50]" :page-size="listQuery.limit" layout="sizes, prev, pager, next, total" :total="total">
      </el-pagination>
    </div>

**Comment by mmd0308** [comment]
好的,谢谢
