### ISSUE TITLE
生产环境中Router为History模式时报错

### ISSUE THREAD

**Issue by xy6321** [PanJiaChen/vueAdmin-template#34]
路由模式改为History后，dev环境一切正常，run build未出现报错。

将build好的文件放入server中，切换页面即报unexpected token < 错误，发现引用js文件的路径有误。

将/config/index.js 中 assetsPublicPath 值从 './' 更改为 '/' 后错误消失。
不知我如此修改是否正确？ @PanJiaChen

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vueAdmin-template/blob/dec0a64ae2c1ebaa8d7ca911143311754e5c3ca6/config/index.js#L10

结合自己实际情况进行修改。一般业务中更改为 '/'  即可

**Comment by xy6321** [comment]
十分感谢！
