### ISSUE TITLE
[Vue warn]: Property or method "key" is not defined. 这个警告是什么情况？

### ISSUE THREAD

**Issue by yichangle** [PanJiaChen/vueAdmin-template#36]
[Vue warn]: Property or method "key" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <AppMain> at src\views\layout\components\AppMain.vue
       <Layout> at src\views\layout\Layout.vue
         <App> at src\App.vue
           <Root>

**Comment by PanJiaChen** [comment]
谢谢提醒，已修复该问题 https://github.com/PanJiaChen/vueAdmin-template/commit/bb0b37e0ebb21515eabdd181b404a62c9b222815
