### ISSUE TITLE
Linux下启动报错

### ISSUE THREAD

**Issue by Ikaris-a** [PanJiaChen/vueAdmin-template#37]
(node:32720) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Exited with code 3
(node:32720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by PanJiaChen** [comment]
非本项目问题 请自行google
