### ISSUE TITLE
跨域是怎么解决的

### ISSUE THREAD

**Issue by xihadandan** [PanJiaChen/vueAdmin-template#39]
项目里没有配置proxy，没看懂您项目是怎么解决的？

**Comment by PanJiaChen** [comment]
本项目使用 `easy-mock` 自带跨域。
详情见 [文档-跨域](https://panjiachen.github.io/vue-element-admin-site/#/cors) && [文档-mock](https://panjiachen.github.io/vue-element-admin-site/#/mock-api)
