### ISSUE TITLE
可以分享下easy mock的数据吗？

### ISSUE THREAD

**Issue by gaoshijun1993** [PanJiaChen/vueAdmin-template#4]
rt，非常感谢~

**Comment by PanJiaChen** [comment]
不是很懂，为什么要看 easy mock 的数据? 如果是数据格式的话。network 里就能看啊？

**Comment by gaoshijun1993** [comment]
因为对easy-mock还不是很熟悉，不太了解怎么针对post内容动态的返回response。。还有在api/login.js 中的function logout中是不是少写了参数？在store/module/user.js中的action中定义调用login的时候有传递state.token进去

**Comment by PanJiaChen** [comment]
easy-mock相关的问题还是建议去看看官方的介绍。
logout的确是少写了参数，不过是mock数据，所以也无所谓，正常业务中应该将相关userID传入告诉后端登出。

**Comment by gaoshijun1993** [comment]
非常感谢~

**Comment by gaoshijun1993** [comment]
你好，关于登陆和获取用户信息我有个疑问，您的代码中是登陆过后返回token，然后传回token参数get方法获取用户信息。请问为什么不在登录过后就返回用户信息？在实际生产过程中是不是在获取用户信息的时候使用post方法，传回用户的id？小白一枚，还请不吝赐教。。

**Comment by PanJiaChen** [comment]
https://segmentfault.com/a/1190000009506097#articleHeader2
你直接登录就返回用户信息是可以的，但你刷新页面该怎么办？再去登录去拿信息？所以本来登录和getInfo本来就是独立的两件事为什么要合在一起？

**Comment by gaoshijun1993** [comment]
非常感谢~
