### ISSUE TITLE
favicon.icon ,你加在哪里呢， 我看了根目录下面的index.html 和 app.vue 文件都没有找到啊。

### ISSUE THREAD

**Issue by dawayway** [PanJiaChen/vueAdmin-template#40]
裤衩哥，favicon.icon ,你加在哪里呢， 我看了根目录下面的index.html 和 app.vue 文件都没有找到啊。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vueAdmin-template/blob/master/favicon.ico
