### ISSUE TITLE
请教一下如何把webSocket事件中的参数传递给vue methods中函数？

### ISSUE THREAD

**Issue by blueroseslol** [PanJiaChen/vueAdmin-template#45]
在创建websocket后可以绑定一些事件：
this.webSocket = new WebSocket(wsUri);
一般是绑定function的
   this.webSocket.onerror =function (Evt) {}；

像这样的参数Evt如何传递到vue的method中的函数呢？
直接(onError()为我再Vue的methods中定义的函数)   
this.webSocket.onerror =this.onError();
可以执行，但是无法传递参数

**Comment by blueroseslol** [comment]
这个是大致代码
https://jsfiddle.net/bluerose/dko6g9a4/

**Comment by PanJiaChen** [comment]
https://jsfiddle.net/dko6g9a4/1/

**Comment by blueroseslol** [comment]
谢谢！
