### ISSUE TITLE
npm install报错，有截图

### ISSUE THREAD

**Issue by fantasy525** [PanJiaChen/vueAdmin-template#46]
- # 操作系统：win10 64位
- # node版本：8.6.0
- # npm 版本：5.3.0
## 截图如下
![image](https://user-images.githubusercontent.com/22516157/34555684-04193622-f16e-11e7-91a1-5d946e302e33.png)

**Comment by fantasy525** [comment]
不用淘宝镜像安装就没有报错了，这怎么回事？淘宝镜像没有同步这个包？

**Comment by PanJiaChen** [comment]
对方源的问题
