### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by zhuzhibei** [PanJiaChen/vueAdmin-template#48]
下载源码执行完npm install，再执行npm run dev报错，源码未做修改。

![20180111111012](https://user-images.githubusercontent.com/8795798/34806831-43880962-f6c0-11e7-946a-6f11ffb53b3e.png)

**Comment by PanJiaChen** [comment]
未能重现你的问题。

**Comment by zhuzhibei** [comment]
不好意思，是我node版本太低了，一年前装的了
