### ISSUE TITLE
Uncaught (in promise) TypeError: roles.some is not a function

### ISSUE THREAD

**Issue by ming7824** [PanJiaChen/vueAdmin-template#5]
當我把連接的api改為遠端,然後用editor登入,結果發現這個錯誤?

**Comment by PanJiaChen** [comment]
你传入的roles不是数组格式吧

**Comment by DaveSteven** [comment]
我也碰到这问题了。我把main.js里router的导航钩子改了一下，GetInfo内，更改了roles为空数组，暂时解决了问题。如果作者有更好的解决方法，麻烦贴一下。

`router.beforeEach((to, from, next) => {
  NProgress.start();
  if (store.getters.token) {
    if (to.path === '/login') {
      next({ path: '/' });
    } else {
      if (store.getters.roles.length === 0) {
        store.dispatch('GetInfo').then(res => {
          // roles改为了空数组
          const roles = [];
          console.log(res.data)
          store.dispatch('GenerateRoutes', { roles }).then(() => {
            router.addRoutes(store.getters.addRouters);
            next({ ...to });
          })
        })
      } else {
        next();
      }
    }
  } else {
    if (whiteList.indexOf(to.path) !== -1) {
      next()
    } else {
      next('/login');
      NProgress.done();
    }
  }
});`

**Comment by DaveSteven** [comment]
我也碰到这问题了。我把main.js里router的导航钩子改了一下，GetInfo内，更改了roles为空数组，暂时解决了问题。如果作者有更好的解决方法，麻烦贴一下，谢谢！
![image](https://user-images.githubusercontent.com/8252276/28804425-ad2d9eb4-7695-11e7-9d84-3c7bbb4fbaf3.png)

**Comment by ming7824** [comment]
感謝,果然是數組問題..

**Comment by DaveSteven** [comment]
![image](https://user-images.githubusercontent.com/8252276/28805527-443bf268-769d-11e7-95d4-077dc9158ea6.png)
我在这里改了一下。

**Comment by ming7824** [comment]
感謝2位幫忙解答
