### ISSUE TITLE
作者在不？你线上模板登录不上去，我下载下来也是一样

### ISSUE THREAD

**Issue by king7329178** [PanJiaChen/vueAdmin-template#51]
https://easy-mock.com/mock/5950a2419adc231f356a6636/vue-admin/user/login     Failed to load resource: net::ERR_INSECURE_RESPONSE

errError: Network Error

 OPTIONS  https://easy-mock.com/mock/5950a2419adc231f356a6636/vue-admin/user/login net::ERR_INSECURE_RESPONSE

你能帮忙解决下么？

**Comment by king7329178** [comment]
大佬，我在线等

**Comment by PanJiaChen** [comment]
easy-mock 挂了

**Comment by xiaozhu188** [comment]
怎么修复

**Comment by PanJiaChen** [comment]
https://github.com/easy-mock/easy-mock
去这里提吧

**Comment by PanJiaChen** [comment]
官方已修复
