### ISSUE TITLE
问下，如果处理sessionId不一致问题

### ISSUE THREAD

**Issue by he0xff** [PanJiaChen/vueAdmin-template#52]
（1）从登录页进去获取sesionId 赋值到cookie中，
（2）在通过token去获取用户信息，此时sessionId竟然不一样了，后台用springboot，根据网上资料设置了
response.setHeader("Access-Control-Allow-Credentials","true"); 
但是还是不行，请教下

**Comment by PanJiaChen** [comment]
其提供更详细的内容

**Comment by he0xff** [comment]
（1）通过login获取获取token,java 后台设置了 request.getSession().setAttribute(token, roleId);
格式{code: **, data: { token : ** }} 然后template根据token设置了cookie
（2）然后会调用 user/info接口，想通过token获取session中的信息，发现这个request.getSession()是一个新的回话，并不是登录模块设置的回话 https://segmentfault.com/a/1190000009208644
谢谢

**Comment by PanJiaChen** [comment]
所以我怎么会知道你具体的错误是什么。
请帖具体代码和实际发送的token和cookie里的token到底是什么

**Comment by he0xff** [comment]
谢谢大神，昨天问题解决了。十分感谢回复。
