### ISSUE TITLE
npm run build:prod和npm run build:sit 无效

### ISSUE THREAD

**Issue by xiaoxintiaoda** [PanJiaChen/vueAdmin-template#53]
请问我项目写完后执行 npm run build:prod和npm run build:sit 都会报错，但是执行npm run build是好的，可以打包出来的是测试环境，我想要打包一个正式环境的，要如何执行呢，我可不可以直接把vue-element-admin build和config目录里面的所有文件直接拷过来使用呢，会有什么问题吗,webpack我不太会，可以帮忙解答一下嘛，谢谢啦！！

**Comment by PanJiaChen** [comment]
本项目不支持多环境打包。有需求的可以参照`vue-element-admin`。主要代码是这里
https://github.com/PanJiaChen/vue-element-admin/blob/94ae1f871934859134f8dab04743d81facd416be/build/webpack.prod.conf.js#L18
通过加载不同的环境变量来区分不同的环境。具体实现方案请自行研究。

**Comment by xiaoxintiaoda** [comment]
>_<

**Comment by Zlmdb** [comment]
没有任何想法
