### ISSUE TITLE
admin和editor的用户名登录写在哪？

### ISSUE THREAD

**Issue by bs2827883** [PanJiaChen/vueAdmin-template#57]
这个template没有Mock我还把export function isvalidUsername(str) {
  const valid_map = ['admin', 'editor']
  return valid_map.indexOf(str.trim()) >= 0
}给删了，但是还是能实现admin和editor才能登录，请问写在哪？

**Comment by PanJiaChen** [comment]
请重新组织一下语言，准确描述一下你目前的问题是什么？

**Comment by bs2827883** [comment]
我想Mock用户名和密码来登录，替换现有的用户名admin和editor。但我发现这个模板项目并没有用Mock，我也找不到您在哪里验证用户名admin和editor。我把/utils/validate/里面的 isvalidUsername删除后，还是只允许admin和editor这两个用户名登录，请问您在哪里写只允许admin和editor这两个用户登录，非常感谢！

**Comment by PanJiaChen** [comment]
本项目使用的的`easy-mock`来模拟数据。
![image](https://user-images.githubusercontent.com/8121621/36524356-aef30710-17e0-11e8-892c-cfb8245f8a9e.png)

我在登录接口中做了用户名的校验，所以你需要切换成自己的mock数据。
