### ISSUE TITLE
run build 的一些问题 dev.env.js文件

### ISSUE THREAD

**Issue by DeloYong** [PanJiaChen/vueAdmin-template#60]
在dev.env.js文件中我进行了更改
`'use strict'
const merge = require('webpack-merge')
const prodEnv = require('./prod.env')

module.exports = merge(prodEnv, {
  NODE_ENV: '"development"',
  BASE_API: '"http://119.23.229.131:8080"',
})`
在运行环境中，是正常的以这个地址进行请求的。
但当我npm run build 打包之后，登录请求又变成了：`Request URL:https://easy-mock.com/mock/5950a2419adc231f356a6636/vue-admin/admin/login`
这是为什么呢？

**Comment by DeloYong** [comment]
并且，我在api文件夹里我更改了登录的请求地址，打包之后均失效了，我很纳闷了。。因为在dev环境中都是正常的，是因为没打包到api文件夹吗

**Comment by PanJiaChen** [comment]
dev.env.js 只对本地环境有效。
npm run build 针对的是线上环境，请修改 https://github.com/PanJiaChen/vueAdmin-template/blob/master/config/prod.env.js

**Comment by DeloYong** [comment]
3Q very much！似乎是编译问题，当我改了prod.env.js之后，build 并没有改为正式地址，但是隔一天在build就成功了  - -！
