### ISSUE TITLE
分页的英文怎么改成中文，他现在总是显示total，我想改成 共 几 页这种形式

### ISSUE THREAD

**Issue by dawayway** [PanJiaChen/vueAdmin-template#62]

**Comment by PanJiaChen** [comment]
请自行设置语言 https://github.com/PanJiaChen/vueAdmin-template/blob/master/src/main.js#L7

详情见http://element-cn.eleme.io/#/zh-CN/component/i18n

**Comment by dawayway** [comment]
谢谢裤衩哥
