### ISSUE TITLE
sideBar的图标样式有问题

### ISSUE THREAD

**Issue by guozuji** [PanJiaChen/vueAdmin-template#67]
![2fd8bf78e96c5b4cfa9c77c0b834993e](https://user-images.githubusercontent.com/27772905/37407231-24649bd2-27d4-11e8-9b0f-aba018d30a15.jpg)
![2018-03-14 10 09 13](https://user-images.githubusercontent.com/27772905/37407406-89051b0c-27d4-11e8-881b-067c4d4d7774.png)
就是这个class 为“el-tooltip” 的标签导致。我用！important强行修改了这个样式。对齐了，但是sideBar打开和收起会闪烁不流畅。请教如何解决。谢谢！
![ele-admin](https://user-images.githubusercontent.com/27772905/37407519-ce0a7238-27d4-11e8-9aca-527922b73cc1.gif)

**Comment by guozuji** [comment]
解决了。我新下载了一个svg 图，换掉就好了

**Comment by logicool** [comment]
@guozuji 请问这个下载svg是git最新的吗？我还是有一样的问题，多出个el-tooltip的div
