### ISSUE TITLE
請問菜單權限問題?

### ISSUE THREAD

**Issue by ming7824** [PanJiaChen/vueAdmin-template#7]
![image](https://user-images.githubusercontent.com/30595619/28903314-c655ee62-7836-11e7-9342-675f4f3b698f.png)

二級菜單可以以下面設定隱藏

 {
    path: '/admin-chart',
    component: Layout,
    redirect: 'noredirect',
    name: 'Admin-Chart',
    icon: 'zujian',
    children: [
            { path: 'index', component: IEcharts, name: 'Line', icon: 'zonghe', meta: { role: ['admin'] } },
            { path: 'bar', component: IEcharts2, name: 'Bar', icon: 'zonghe', meta: { role: ['admin'] } },
            { path: 'pie', component: IEcharts3, name: 'Pie', icon: 'zonghe', meta: { role: ['admin'] } },
            { path: 'map', component: IEcharts4, name: 'Map', icon: 'zonghe', meta: { role: ['admin'] } }
    ]
  },
那一級菜單是否可以隱藏?

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/28904824-34f53590-7840-11e7-9f82-52a85e681c57.png)

同理一样用meta role 来判断
