### ISSUE TITLE
 [vue-router] "path" is required in a route configuration

### ISSUE THREAD

**Issue by hjx5309** [PanJiaChen/vueAdmin-template#72]
以下是我的router的代码，为何老是报上面的错呢？
import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

export const constantRouterMap = [ 
  { path: '/404', component: () => import('@/views/404') , hidden: true },
  { path: '*', redirect: '/404', hidden: true }
]

export default new Router({
  routes: [
    {
      scrollBehavior: () => ({ y: 0 }),
      routes: constantRouterMap
    }
  ]
})

**Comment by PanJiaChen** [comment]
我猜测是你声明了两层<router-view>，但你的路由里面只有一层所以会报错。
你在声明一个嵌套路由试试，如：
```js
{
    path: '/theme',
    component: Layout,
    redirect: 'noredirect',
    children: [{ path: 'index', component: _import('theme/index'), name: 'theme', meta: { title: 'theme', icon: 'theme' }}]
  },
```

**Comment by hjx5309** [comment]
问题解决了
