### ISSUE TITLE
权限结果疑惑？

### ISSUE THREAD

**Issue by xdwxls** [PanJiaChen/vueAdmin-template#73]
![image](https://user-images.githubusercontent.com/9478777/38465689-95693d5c-3b51-11e8-9ef5-ead8e072c494.png)

看获取user 信息  返回字段有role，roles 内容一样，请问下这两个字段的区别和用途

**Comment by PanJiaChen** [comment]
谢谢你的提醒，目前主需要roles.
role是为了兼容老的api。已去除。历史原因。

**Comment by xdwxls** [comment]
@PanJiaChen 好的，还有一个疑惑 roles 为啥用数组，而不是一个字符串，难道是为了一个账号可能拥有多种角色考虑？

**Comment by PanJiaChen** [comment]
是的。
