### ISSUE TITLE
permission-control分支登录异常

### ISSUE THREAD

**Issue by shilikeji** [PanJiaChen/vueAdmin-template#77]
路径:src/permission.js  16行获取GetInfo接口返回内容时，参数名和接口返回名不一致，导致角色为空报错。

接口返回roles 获取时使用role

**Comment by he-xiangdong** [comment]
后面 还是报错

![admin-error](https://user-images.githubusercontent.com/30164123/38915063-e8cd47de-4314-11e8-87bf-5d0fb1a88bd5.png)

**Comment by Webwwl** [comment]
user.js 48行 commit('SET_ROLES', data.role)  少了个s 应该是roles 
permission.js  16行 const roles = res.data.role 也少了个s
改了这两处就好了

**Comment by PanJiaChen** [comment]
这周我会更新一下的。

**Comment by PanJiaChen** [comment]
已更新。
