### ISSUE TITLE
请问，页面切换时，不重新加载，该怎么配置？

### ISSUE THREAD

**Issue by ninki51** [PanJiaChen/vueAdmin-template#8]

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vueAdmin-template/blob/master/src/views/layout/AppMain.vue#L4
修改为：
```html
 <keep-alive>
   <router-view></router-view>
 </keep-alive>
```

去掉router-view上的key，并增加keep-alive

**Comment by ninki51** [comment]
感谢大神的指点
