### ISSUE TITLE
侧边栏交互体验问题

### ISSUE THREAD

**Issue by ChasonHong** [PanJiaChen/vueAdmin-template#81]
pc端侧边栏点击按键侧边栏显示隐藏，右边主体内容跟随这个没有问题但是在
小屏上比如手机模式，还是跟pc一样的交互，需要修改为手机端查看 点击按键侧边栏显示上一层级，右边内容不要被跟随，这样在手机端侧边栏显示时，右边主体内容就不会被往右边移，参考例子：
https://lanux.github.io/Vue-Admin/#/

**Comment by PanJiaChen** [comment]
很好的建议。

**Comment by ChasonHong** [comment]
@PanJiaChen 能改造下嘛，你这个组件比较全面，想用你这套，但是不知道怎么改

**Comment by PanJiaChen** [comment]
v3.6.0版本已添加
