### ISSUE TITLE
permission-control的elementUI版本太低

### ISSUE THREAD

**Issue by horizontung** [PanJiaChen/vueAdmin-template#85]
permission-control分支的elementUI版本太低了，升级到最新版本，主题颜色恢复默认了，不少bug，期待希望大神早点更新下这个分支

**Comment by horizontung** [comment]
@PanJiaChen 而且发现permission-control分支，在左边menu在路由上的设置也有问题，是通过noDropdown 参数设置是否为根菜单，而不是像主分支那样根据路由的children数量自行判断的。这个分支真版本真挺老了，期待最新版本。

**Comment by PanJiaChen** [comment]
已更新。
