### ISSUE TITLE
切换语言时 侧导航，面包屑切换失败。

### ISSUE THREAD

**Issue by xiangrui09** [PanJiaChen/vueAdmin-template#87]
utils/i18n.js 文件中
hasKey 总是输出 false
```
console.log(title)  == Form
console.log(hasKey) ==  false
console.log(translatedTitle)  == route.Form
```

lang/index.js 打印 i18n.messages ，route语言包是存在的。
![lang-index](https://user-images.githubusercontent.com/12625122/39301710-b2e512c2-4982-11e8-814d-a1a91254ac02.png)

vue模板中使用的是 {{generateTitle(child.meta.title)}}方法

**Comment by PanJiaChen** [comment]
你提供的代码太零散了，很难get到你到底想表达什么，请提供更详细的描述。最好结合错误来描述。

**Comment by xiangrui09** [comment]
我在模板中引入了 i18n 做语言切换

> main.js 
> ``` 
> import i18n from './lang'
> ...
> Vue.use(Element, {
>   i18n: (key, value) => i18n.t(key, value)
> })
> ...
> new Vue({
>   el: '#app',
>   ...
>   i18n,
>   ...
> })
> ```


> package.json
> ```
> "vue-i18n": "^7.3.2",
> ```

引入后
在页面中用 `{{$t()}}` 输出的文本，语言切换正常。
登录后的页面使用 js 方法 `generateTitle` 的文本，切换语言失败。

lang 文件夹的内容与 https://github.com/PanJiaChen/vue-element-admin/tree/master/src/lang 是一样的。

> utils/i18n.js
> ```
> export function generateTitle(title) {
>   const hasKey = this.$te('route.' + title)
>   const translatedTitle = this.$t('route.' + title) 
>   console.log(title) // Form
>   console.log(hasKey) // false
>   console.log(translatedTitle) // route.Form
>   if (hasKey) {
>     return translatedTitle
>   }
>   return title
> }
> 
> ```

错误提示是  
[vue-i18n] Value of key 'route.Tree' is not a string!
[vue-i18n] Cannot translate the value of keypath 'route.Tree'. Use the value of keypath as default.

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/lang/en.js#L2

导航这块的翻译需要多一个route{}。
` const translatedTitle = this.$t('route.' + title) `
当然你也可以修改 `generateTitle`这个函数。

**Comment by xiangrui09** [comment]
route.form 也报同样的错

**Comment by xiangrui09** [comment]
找到原因了 . 大小写敏感。
