### ISSUE TITLE
Loading PostCSS Plugin failed: Cannot find module 'postcss-url'

### ISSUE THREAD

**Issue by horizontung** [PanJiaChen/vueAdmin-template#89]
更新后的master和permission-control分支运行npm run dev都会报5个错，都是Loading PostCSS Plugin failed: Cannot find module 'postcss-url'这样的。我是自行运行 npm install --save-dev postcss-url解决的。大神这个包为什么不写进package.json呢？

**Comment by PanJiaChen** [comment]
已修复，谢谢你的反馈。

**Comment by horizontung** [comment]
不用谢，大神写的模板很好，文档也很详细，学到了不少东西呢。
