### ISSUE TITLE
请问next（）的几种写法的区别？

### ISSUE THREAD

**Issue by gaoshijun1993** [PanJiaChen/vueAdmin-template#9]
如题，在main.js中写了next（{...to}),这种写法和next（to.path),nxet(to)有什么区别？

**Comment by PanJiaChen** [comment]
next（{...to}) 拷贝对象
其他两个字面意思咯。。。

**Comment by gaoshijun1993** [comment]
您的代码中分别用到了next(),next(to.path)和next({...to})这三种写法，我对这三种写法的效果的区别不是很理解，在我的测试中，貌似都跟next()效果一样

**Comment by PanJiaChen** [comment]
完全不是一个意思。。。next()会直接释放钩子，next(xxx)会重新进入钩子
next(to.path) 这样会丢失to这个对象上其它的属性如query meta等。

**Comment by gaoshijun1993** [comment]
非常感谢解答，还有就是在src/utils/fetch.js文件中，第51行中的return Promise.reject(error)，这里应该是写多了error参数

**Comment by PanJiaChen** [comment]
@gaoshijun1993 感谢提醒
